services:
  - type: web
    name: heart-attack-risk-predictor
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8051
    healthCheckPath: /_stcore/health
